### ISSUE TITLE
Get Error at first time initial

### ISSUE THREAD

**Issue by oblin** [sergey-brutsky/mi-home#14]
it will get 0 devices first time,
and get error message when dispose miHome object, error:

```
The given key 'ctrl_ln2.aq1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MiHomeLib.MiHome.GetOrAddDeviceByCommand(ResponseCommand cmd)
   at MiHomeLib.MiHome.ProcessReport(ResponseCommand cmd)
   at MiHomeLib.MiHome.StartReceivingMessages(CancellationToken ct)

```   
but if i use debugger go back to new MiHome, it will get devices (but not aqua wall switch)

And the above error will continue display.

Please help, thanks.

**Comment by sergey-brutsky** [comment]
Hi oblin, it looks like a new device which is not supported by library (crtrl_ln2.aq1).
Could you please add support for the device and send me pull request ?

**Comment by sergey-brutsky** [comment]
Closed due to no response from the author
